workflows:
  flutter-app:
    name: "Flutter Application"
    environment:
      flutter: stable
      xcode: latest  # Указывает последнюю доступную версию Xcode
      cocoapods: default  # Использует последнюю версию CocoaPods
    scripts:
      - name: Install Flutter
        script: |
          flutter channel stable
          flutter upgrade
          flutter doctor
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign  # Собирает iOS без подписи кода
