workflows:
  flutter-app:
    name: "Flutter Application"
    environment:
      flutter: stable
    scripts:
      - name: Install Flutter
        script: |
          flutter channel stable
          flutter upgrade
          flutter doctor
      - name: Install dependencies
        script: flutter pub get
      - name: Build
        script: flutter build apk --release
