# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'cloud_firestore', :path => '.symlinks/plugins/cloud_firestore/ios'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
